name: Android CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "feature/**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Build Debug
        run: ./gradlew assembleDebug

      - name: Run unit tests
        run: ./gradlew test
